let words =[ {
    question:"brave",
    options:["courage","fear","sad"],
    answer:"courage"
},
    {
    question:"endure",
    options:["persist","flaw","strange"],
    answer:"persist"
},
{
    question:"harass",
    options:["reason","observant","torment"],
    answer:"torment"
},
{
    question:"baffle",
    options:["confuse","clear","transparent"],
    answer:"confuse"
},
]
